export declare function stump(opts: options): void;
export interface dispatcher {
    ondispatch: ondispatch;
}
export declare type options = {
    targetID: string;
    view: view;
    state: state;
    dispatchers: dispatcher[];
};
export declare type view = (state: state) => component;
export declare type state = {
    [key: string]: any;
};
export declare type component = {
    type: string;
    children?: child[];
    options?: componentOpts;
};
export interface componentOpts {
    [key: string]: any;
    onabort?: event;
    onanimationcancel?: event;
    onanimationend?: event;
    onanimationiteration?: event;
    onauxclick?: event;
    onblur?: event;
    oncancel?: event;
    oncanplay?: event;
    oncanplaythrough?: event;
    onchange?: event;
    onclick?: event;
    onclose?: event;
    oncontextmenu?: event;
    oncopy?: event;
    oncuechange?: event;
    oncut?: event;
    ondblclick?: event;
    ondurationchange?: event;
    onended?: event;
    onerror?: event;
    onfocus?: event;
    onformdata?: event;
    ongotpointercapture?: event;
    oninput?: event;
    oninvalid?: event;
    onkeydown?: event;
    onkeypress?: event;
    onkeyup?: event;
    onload?: event;
    onloadeddata?: event;
    onloadedmetadata?: event;
    onloadend?: event;
    onloadstart?: event;
    onlostpointercapture?: event;
    onmousedown?: event;
    onmouseenter?: event;
    onmouseleave?: event;
    onmousemove?: event;
    onmouseout?: event;
    onmouseover?: event;
    onmouseup?: event;
    onpaste?: event;
    onpause?: event;
    onplay?: event;
    onplaying?: event;
    onpointercancel?: event;
    onpointerdown?: event;
    onpointerenter?: event;
    onpointerleave?: event;
    onpointermove?: event;
    onpointerout?: event;
    onpointerover?: event;
    onpointerup?: event;
    onreset?: event;
    onresize?: event;
    onscroll?: event;
    onselect?: event;
    onselectionchange?: event;
    onselectstart?: event;
    onsubmit?: event;
    ontouchcancel?: event;
    ontouchstart?: event;
    ontransitioncancel?: event;
    ontransitionend?: event;
    onwheel?: event;
}
export declare type ondispatch = (dispatch: dispatch) => void;
export declare type dispatch = (fn: response) => void;
export declare type response = (state: state) => state;
export declare type eventValue = (Event | any);
export declare type event = (evt: eventValue, dispatch: dispatch) => void;
export declare type action = (evt: eventValue, state: state) => state;
export declare type element = Element | ChildNode;
export declare type maybeelement = element | undefined;
export declare type child = component | string;
export declare type maybechild = child | undefined;
export declare const c: (c: component) => {
    type: string;
    children: child[];
    options: componentOpts;
};
export declare const dispatcher: (fn: ondispatch) => dispatcher;
export declare const response: (fn: response) => dispatcher;
export declare const action: (fn: action) => (event: Event, dispatch: dispatch) => void;
