export declare function stump(opts: options): void;
export interface dispatcher {
    ondispatch: ondispatch;
}
export declare type options = {
    targetID: string;
    view: view;
    state: state;
    dispatchers: dispatcher[];
};
export declare type view = (state: state) => component;
export declare type state = {};
export declare type component = {
    type: string;
    children: (component | string)[];
    options: componentOpts;
};
export interface componentOpts {
    [key: string]: any;
    onabort: maybeevent;
    onanimationcancel: maybeevent;
    onanimationend: maybeevent;
    onanimationiteration: maybeevent;
    onauxclick: maybeevent;
    onblur: maybeevent;
    oncancel: maybeevent;
    oncanplay: maybeevent;
    oncanplaythrough: maybeevent;
    onchange: maybeevent;
    onclick: maybeevent;
    onclose: maybeevent;
    oncontextmenu: maybeevent;
    oncopy: maybeevent;
    oncuechange: maybeevent;
    oncut: maybeevent;
    ondblclick: maybeevent;
    ondurationchange: maybeevent;
    onended: maybeevent;
    onerror: maybeevent;
    onfocus: maybeevent;
    onformdata: maybeevent;
    ongotpointercapture: maybeevent;
    oninput: maybeevent;
    oninvalid: maybeevent;
    onkeydown: maybeevent;
    onkeypress: maybeevent;
    onkeyup: maybeevent;
    onload: maybeevent;
    onloadeddata: maybeevent;
    onloadedmetadata: maybeevent;
    onloadend: maybeevent;
    onloadstart: maybeevent;
    onlostpointercapture: maybeevent;
    onmousedown: maybeevent;
    onmouseenter: maybeevent;
    onmouseleave: maybeevent;
    onmousemove: maybeevent;
    onmouseout: maybeevent;
    onmouseover: maybeevent;
    onmouseup: maybeevent;
    onpaste: maybeevent;
    onpause: maybeevent;
    onplay: maybeevent;
    onplaying: maybeevent;
    onpointercancel: maybeevent;
    onpointerdown: maybeevent;
    onpointerenter: maybeevent;
    onpointerleave: maybeevent;
    onpointermove: maybeevent;
    onpointerout: maybeevent;
    onpointerover: maybeevent;
    onpointerup: maybeevent;
    onreset: maybeevent;
    onresize: maybeevent;
    onscroll: maybeevent;
    onselect: maybeevent;
    onselectionchange: maybeevent;
    onselectstart: maybeevent;
    onsubmit: maybeevent;
    ontouchcancel: maybeevent;
    ontouchstart: maybeevent;
    ontransitioncancel: maybeevent;
    ontransitionend: maybeevent;
    onwheel: maybeevent;
}
export declare type ondispatch = (dispatch: dispatch) => void;
export declare type dispatch = (fn: response) => void;
export declare type response = (state: state) => state;
export declare type event = (evt: Event, dispatch: dispatch) => void;
export declare type action = (evt: Event, state: state) => state;
declare type child = component | string;
declare type maybeevent = event | undefined;
export declare const c: (opts: component) => {
    type: string;
    children: child[];
    options: componentOpts;
};
export declare const dispatcher: (fn: ondispatch) => dispatcher;
export declare const response: (fn: response) => dispatcher;
export declare const action: (fn: action) => (event: Event, dispatch: dispatch) => void;
export {};
